### ISSUE TITLE
*Important* reading from modules during run

### ISSUE THREAD

**Issue by spaulaus** [pixie16/PixieSuite2#11]
__Bad__ idea. Can corrupt set files and crash modules. 

May be speaking from personal experience......

**Comment by ksmith0** [comment]
Possibility of this was removed in commit 32f746cb99047aa7f06fae6266c315c618625095. This resolves the bug status. I believe this should be further researched to explore whether it is viable as it would be a nice feature. Perhaps instead of reading directly form the module we read from a database of their values.
