### ISSUE TITLE
Monitor does not report correct statistics

### ISSUE THREAD

**Issue by spaulaus** [pixie16/PixieSuite2#2]
When using pacman mode the monitor program does not report the proper statistics. With 24 kHz into 10 channels the rates in the monitor are not correct (~16 kHz). When dropping the rate less than 10 kHz all values are correct. The problem is more significant in PACMAN mode, reporting 200 Hz. 

**This is an issue with how the rate statistics are calculated.**  We should update to use the ICR/OCR from the modules.

**Comment by ksmith0** [comment]
I believe you are describing two different issues. The first is that the reported rates do not correspond to the actual rates due to dead time on the channel from taking traces. These difference are seen while running poll2 without the pacman mode and simply adjusting the rate.

Secondly, the pacman mode of poll2 is acquiring at even lower rates than poll2 without the pacman mode.

I do not believe this is an issue with the calculation in either case.  In the first case we should continue to use these scalers as they provide us with the rate of event acquired and additionally add OCR and ICR. In the second case, I believe that there is a severe limitation in the pacman mode implementation.

**Comment by ksmith0** [comment]
Added monitor branch to investigate.

**Comment by ksmith0** [comment]
The pacman mode issue was due to a threading issue. The loop listening for pacman was in the run thread. This was moved to the command thread, which required the addition of a timeout to the terminal. These features were added in commit 7effa6 and slightly adjusted fro the ISOLDE setup in commit a70eab3a7ec5.

**Comment by ksmith0** [comment]
The first issue was as described, when taking traces the rate is reduced as the trace window is larger than the period between triggers. The addition of ICR and OCR to the monitor in commit  e05af5b51f4026536 help clarify this.
