### ISSUE TITLE
pixie.cfg overwritten by install

### ISSUE THREAD

**Issue by spaulaus** [pixie16/PixieSuite2#8]
Commit c728fd81462f08f7d0d66f725257b690c99e3012 on dev branch does not resolve the issue of the config file being overwritten during installation.

**Comment by ksmith0** [comment]
It does in some cases. I observed this as well. I believe it was because the commit moved the file causing the timestamp to be updated and newer than that of the file stored in the exec directory. After a make install the file is overwritten. This mean that anytime a commit touches the share/pixie.cfg the user defined version will be overwritten. This is definitely not the best situation. If you update your pixie.cfg after pulling the commit then the file is not overwritten.

**Comment by ksmith0** [comment]
Finally resolved, by commit 5bd7f9cfb720c3bf5521f6985c445ee0ba4de523. Typing make config will create the config files overwriting slot_def.set, current.set and pixie.cfg.
